jekyll:
    image: jekyll/jekyll:latest
    command: bash -c "gem install bundler:1.17.2 && touch Gemfile.lock && chmod a+w Gemfile.lock && jekyll serve --force_polling"
    ports:
        - 4000:4000
    volumes:
        - .:/srv/jekyll
