on:
  pull_request:
# 어느 브랜치에 푸시할때 동작할지
name: Deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      PORT: 4000
    steps:
    - run: docker-compose -f $(pwd)/docker-compose.yml up 